export const FETCH_EVENTS_AND_RELATIONS = 'FETCH_EVENTS_AND_RELATIONS'
// export const FETCH_SINGLE_TICKET = 'FETCH_SINGLE_TICKET'
export const NEXT_PAGE = 'NEXT_PAGE'
export const PREVIOUS_PAGE = 'PREVIOUS_PAGE'
