http://localhost:4000/events?pageNum=1
###
http://localhost:4000/events/filter?name=soap&date=

###
http://localhost:4000/auth
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzIsImlhdCI6MTUzNDg5NDM1NCwiZXhwIjoxNTM1NDk5MTU0fQ.cnLOER6AI8DJ3ego5mTQ5bz3VcW9xakx6lDNEobK8XA
###
DELETE http://localhost:4000/events/33
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzEsImFkbWluIjp0cnVlLCJpYXQiOjE1MzUwNTM2ODMsImV4cCI6MTUzNTY1ODQ4M30.fx-M6ZpdlLUEdlPj7qThs3FYzKYGcK21nvFubNB28Ys
###
PATCH http://localhost:4000/events/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzEsImFkbWluIjp0cnVlLCJpYXQiOjE1MzUwNTM2ODMsImV4cCI6MTUzNTY1ODQ4M30.fx-M6ZpdlLUEdlPj7qThs3FYzKYGcK21nvFubNB28Ys

{
  "name":"test",
  "description": "test",
  "image": "https://source.unsplash.com/random",
  "startDate": "2018-07-12",
  "endDate": "2019-01-01"
}
###
http://localhost:4000/events/test

###
http://localhost:4000/tickets/1

###
POST http://localhost:4000/tickets/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzIsImlhdCI6MTUzNDg5NDM1NCwiZXhwIjoxNTM1NDk5MTU0fQ.cnLOER6AI8DJ3ego5mTQ5bz3VcW9xakx6lDNEobK8XA

{
  "price": 0,
  "description": "aihsoetnah",
  "image": "imageurl"
}

###
http://localhost:4000/users
###
POST http://localhost:4000/users
Content-Type: application/json

{
  "email":"asht@ahst.asht",
  "firstName": "Hajime",
  "lastName": "Suzuki",
  "password": "ashtasht"
}
###
POST http://localhost:4000/users/logins
Content-Type: application/json

{
  "email":"asht@asht.asht",
  "password": "ashtasht"
}

###
http://localhost:4000/users/count-tickets/42

###
http://localhost:4000/users/

###

http://localhost:4000/users/test

###
POST http://localhost:4000/users
Content-Type: application/json

{
  "firstName": "Hajime",
  "lastName": "Suzuki",
  "email": "email@email.com",
  "password": "ashtasht"
}
###

POST http://localhost:4000/logins
Content-Type: application/json

{
  "firstName": "Hajime",
  "lastName": "Suzuki",
  "email": "email@email.com",
  "password": "ashtasht"
}

###
http://localhost:4000/populate


